export const ADD_BURGER_ITEM = 'ADD_BURGER_ITEM';
export const REMOVE_BURGER_ITEM = 'REMOVE_BURGER_ITEM';
export const CHANGE_BURGER_ING_INDEX = 'CHANGE_BURGER_ING_INDEX';
export const REMOVE_ALL_BURGER_ITEM = 'REMOVE_ALL_BURGER_ITEM';