//feed
export const FEED_WS_CONNECTION_START = 'FEED_WS_CONNECTION_START';
export const FEED_WS_CONNECTION_SUCCESS = 'FEED_WS_CONNECTION_SUCCESS';
export const FEED_WS_CONNECTION_ERROR = 'FEED_WS_CONNECTION_ERROR';
export const FEED_WS_CONNECTION_CLOSED = 'FEED_WS_CONNECTION_CLOSED';
export const FEED_WS_GET_MESSAGE = 'FEED_WS_GET_MESSAGE';
export const FEED_WS_SEND_MESSAGE = 'FEED_WS_SEND_MESSAGE';

//user orders
export const UORDER_WS_CONNECTION_START = 'UORDER_WS_CONNECTION_START';
export const UORDER_WS_CONNECTION_SUCCESS = 'UORDER_WS_CONNECTION_SUCCESS';
export const UORDER_WS_CONNECTION_ERROR = 'UORDER_WS_CONNECTION_ERROR';
export const UORDER_WS_CONNECTION_CLOSED = 'UORDER_WS_CONNECTION_CLOSED';
export const UORDER_WS_GET_MESSAGE = 'UORDER_WS_GET_MESSAGE';
export const UORDER_WS_SEND_MESSAGE = 'UORDER_WS_SEND_MESSAGE';